### ISSUE TITLE
Single list element causes clojure.lang.PersistentVector cannot be cast to clojure.lang.Name

### ISSUE THREAD

**Issue by jtmarmon** [Yuppiechef/datomic-schema#10]
This is perhaps the most befuzzling thing I've come across in a while.

I have a big vector of schemas generated by this library. They are all returned by `(get-all-schemas)` which has the job of loading all the schemas in from the namespaces under `api.datomic-schemas.*`.

When I call `(s/generate-schema (get-all-schemas))`, I get 

`CompilerException java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to clojure.lang.Named`

Hmm...surely there must be an issue with an element or two in this array

_after much debugging_

```clj
; Like nth but removes instead of retrieves the item
(defn drop-nth [n coll] (->> coll (map vector (iterate inc 1)) (remove #(zero? (mod (first %) n))) (map second)))

(s/generate-schema (drop-nth 5 (get-all-schemas))) ; Error
(s/generate-schema (drop-nth 10 (get-all-schemas))) ; Error
(s/generate-schema (drop-nth 12 (get-all-schemas))) ; Error
(s/generate-schema (drop-nth 18 (get-all-schemas))) ; No error! 18 is the problem child

; To confirm:

(s/generate-schema (vector (nth (get-all-schemas) 18))) ; No error

;  wat
```

Here's the value of `(vector (nth (get-all-schemas) 18))`

```clj
[{:fields {"description" [:string #{}], "weight" [:double #{}], "genus" [:string #{}]}, :name "species", :basetype :species, :namespace "species"}]
```

UPDATE:

Removed the "problem-child" schema to see if it would work without it. Same error, different schema BUT still number 18. Does this library somehow have a problem with the number 18? There are 30 total schemas returned by (get-all-schemas)

**Comment by CmdrDats** [comment]
Hi, that is indeed strange.. That schema looks rather benign! Perhaps there's something odd about 17 instead that sets 18 up for failure? I can't imagine how though...

Could you pop in a full as possible stacktrace along with as small as possible schema that fails? ie - drop n >= 12, take m until fail?

PS. I notice drop-nth drops on index mod n - is it possible that it drops 18, 36, 54, 72? you did say 'big vector'..

**Comment by jtmarmon** [comment]
@CmdrDats 

Just checked the full stacktrace and found the error is on this invocation https://github.com/Yuppiechef/datomic-schema/blob/master/src/datomic_schema/schema.clj#L42

```
at clojure.core$name.invoke(core.clj:1518)
	at datomic_schema.schema$field__GT_datomic.invoke(schema.clj:42)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$partial$fn__4232.doInvoke(core.clj:2472)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.core.protocols$fn__6074.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at datomic_schema.schema$schema__GT_datomic.invoke(schema.clj:69)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$partial$fn__4228.doInvoke(core.clj:2468)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core.protocols$fn__6093.invoke(protocols.clj:98)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6076.invoke(protocols.clj:60)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at datomic_schema.schema$generate_schema.invoke(schema.clj:83)
	at datomic_schema.schema$generate_schema.invoke(schema.clj:81)
	at api.core$eval9767.invoke(core.clj:68)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.load(Compiler.java:7130)
```

**Comment by jtmarmon** [comment]
ahah! figured it out. your intuition about something funky with number 17 was correct.
 
17 was:

```clj
(schema thing
  (fields
    [field [:a :b :c] :many])))
```

Was missing the enum identifier!

Thanks a bunch :dancer:

**Comment by CmdrDats** [comment]
Fantastic - glad you got it sorted out :) Please could you open a ticket for me to make it more obvious where the problem - throw a "Your schema `thing` on `field` does not seem to have a valid type: [:a :b :c]" would be a whole lot nicer to have for everyone - If you're feeling generous, a PR would be even better! :)
